[package]
name = "hourglass"
version = "0.1.0"
edition = "2021"

[workspace]
default-members = ["apps/*"]
members = ["apps/*", "crates/*"]

[dependencies]
app = { path = "crates/app" }
bus = { path = "crates/bus" }
ecs = { path = "crates/ecs" }
graph = { path = "crates/graph" }
